name = "Locale"

max_age = "last-digest"

[[feeds]]
url = "https://laprovinciapavese.gelocal.it/rss/finegil/laprovinciapavese/feed.rss"
name = "La Provincia Pavese"
max_articles = 30

[[feeds]]
url = "https://www.ilgiorno.it/milano/rss"
name = "Il Giorno Milano"
max_articles = 20

[[feeds]]
url = "https://politepol.com/fd/cgDyyS2NC0Fa.xml"
name = "Albo Pretorio"
max_articles = 40
follow_article_links = true

[llm_settings]
n_most_important_news = 7
k_words_each_summary = 100

[content_extraction_settings]
collection_prompt = "Una panoramica completa ma concisa delle notizie di natura *politica*. Questa rassegna *esclude* tutto ci√≤ che riguarda la cronaca nera, gli eventi locali, le notizie sportive e culturali, a meno che non abbiano un impatto significativo sulla politica di Pavia e/o della Lombardia. *Non include* notizie della politica nazionale o internazionale che vengono riportate da testate locali. Include i dibattiti e le dichiarazioni dei politici comunali, assessori comunali, consiglieri comunali. Include notifiche di atti e decisioni del Comune di Pavia importanti, non i semplici atti quotidiani."
follow_article_links = false
link_filter_pattern = "https:\/\/pavia.trasparenza-valutazione-merito.it\/web\/trasparenza\/papca-ap.+"
